###########################
####### README FIRST! #####
###########################
# This file should only be edited in our main repository (inexor-core)
# You are doing something wrong
# if you are trying to edit this file in the master branch of ci-prebuilds.
#
# Our automation is grabbing the version of this file from our main repository
# and commit it with automatic changes to ci-prebuilds
# and only when Conan dependencies are actually changed
# in order to not cause unnecessary rebuilds.
#
# The ci-prebuilds version will have un-comment every line starting with #CI(followed by an empty space)
# e.g. #CI echo this only gets executed in ci-prebuilds
#
# The ci-prebuilds version will have every line removed containing #CIDELETE
# e.g. #CIDELETE this line is not visible in ci-prebuilds aka. won't get executed
#

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 15

language: cpp

linux: &linux
  os: linux
  sudo: required
  dist: trusty
  services:
    - docker

osx: &osx
  os: osx
  sudo: false
  language: generic

jobs:
  include:
  # We run the following jobs in our main repository:    #CIDELETE
    - stage: "Conan prebuilds triggering"                #CIDELETE
      os: linux                                          #CIDELETE
      dist: trusty                                       #CIDELETE
      sudo: false                                        #CIDELETE
      env: DOCKER="NODOCKER" conan_prebuilds="true"      #CIDELETE
    - stage: "Building & Testing"                        #CIDELETE
      <<: *linux                                         #CIDELETE
      env: COMPILER="clang" COMPILER_VERSION="5.0" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-clang050" NIGHTLY="true" #CIDELETE
    - <<: *linux                                         #CIDELETE
      env: COMPILER="gcc" COMPILER_VERSION="7" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-gcc07" NIGHTLY="true" #CIDELETE
    - stage: "Create GitHub Tag"                         #CIDELETE
      if: branch = master AND tag is blank AND fork is false AND type != pull_request AND repo = head_repo #CIDELETE
      os: linux                                          #CIDELETE
      sudo: false                                        #CIDELETE
      dist: trusty                                       #CIDELETE
      env: DOCKER="NODOCKER" TARGET=new_version_tagger   #CIDELETE
      branches:                                          #CIDELETE
        only:                                            #CIDELETE
          - master                                       #CIDELETE
    #- os: linux                                         #CIDELETE
      #sudo: false                                       #CIDELETE
      #dist: trusty                                      #CIDELETE
      #env: DOCKER="NODOCKER" TARGET=apidoc              #CIDELETE


    # We run the following jobs in ci-prebuilds:
    # Our main compilers we run tests for
    #CI - <<: *osx
      #CI osx_image: xcode9.2
      #CI env: COMPILER="clang" COMPILER_CONFIGURATION="Release" TARGET="macos" DOCKER="NODOCKER" NIGHTLY="conan"
    #CI - <<: *osx
      #CI osx_image: xcode9.2
      #CI env: COMPILER="clang" COMPILER_CONFIGURATION="Debug" TARGET="macos" DOCKER="NODOCKER" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="5.0" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-clang050" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="5.0" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-clang050" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="7" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-gcc07" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="7" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-gcc07" NIGHTLY="conan"

    # Older compilers we compile Conan packages for, to speed things up for other people
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="4.0" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-clang040" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="4.0" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-clang040" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="6" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-gcc06" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="6" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-gcc06" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="5" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-gcc05" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="gcc" COMPILER_VERSION="5" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-gcc05" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="3.9" COMPILER_CONFIGURATION="Release" TARGET="compile" DOCKER="ubuntu-bionic-clang039" NIGHTLY="conan"
    #CI - <<: *linux
      #CI env: COMPILER="clang" COMPILER_VERSION="3.9" COMPILER_CONFIGURATION="Debug" TARGET="compile" DOCKER="ubuntu-bionic-clang039" NIGHTLY="conan"

  #CI fast_finish: true # don't wait for allow_failures to fail, gives faster response
  #CI allow_failures:
    #CI - os: osx
    #CI - os: linux


before_install:
  # Get our CI Docker image
  - if ! [[ "${DOCKER}" == 'NODOCKER' ]]; then
        sudo docker pull inexorgame/ci-docker':'${DOCKER} ;
    fi

script:
  - if [ "${conan_prebuilds}" == "true" ]; then
      bash ./tool/travis_conditional_conan_package_generating.sh ;
    else
      echo "${conan_prebuilds}" ;
    fi
  - if [ "${GLOBAL_NIGHTLY}" == "false" ]; then
      NIGHTLY="false";
    fi
  - if [ "${GLOBAL_NIGHTLY}" == "conanforcerebuild" ]; then
      TARGET="conanforcerebuild";
    fi
  - if [ "${GLOBAL_NIGHTLY}" == "conan" ]; then
      NIGHTLY_USER="${CONAN_USER}";
      NIGHTLY_PASSWORD="${CONAN_PASSWORD}";
    else
      NIGHTLY_USER="${FTP_USER}";
      NIGHTLY_PASSWORD="${FTP_PASSWORD}";
    fi
  - if [[ "${TRAVIS_REPO_SLUG}" == "inexorgame/inexor-core" ]]; then
      if [[ ! "${TRAVIS_PULL_REQUEST}" == false ]]; then
        echo >&2 -e "Skipping build, because this is a pull " \
          "request with a branch in the main repo.\n"         \
          "This means, there should already be a CI job for " \
          "this branch. No need to do things twice.";
        exit 0;
      fi;
    fi;
    if ! [[ "${DOCKER}" == "NODOCKER" ]]; then
      sudo docker run -v $(pwd)':'/inexor --net=host -it inexorgame/ci-docker':'${DOCKER} /inexor/${RELATIVE_PATH}tool/travis.sh ${TARGET} ${COMPILER} ${COMPILER_VERSION} ${COMPILER_CONFIGURATION} ${NIGHTLY} ${NIGHTLY_USER} ${NIGHTLY_PASSWORD} ${FTP_DOMAIN};
    fi;
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      bash ${RELATIVE_PATH}tool/travis_macos.sh;
    fi;
  - if [ "${TARGET}" == "new_version_tagger" ]; then
        bash ./tool/travis.sh ${TARGET} ${COMPILER} ${COMPILER_VERSION} ${COMPILER_CONFIGURATION} ${NIGHTLY} ${NIGHTLY_USER} ${NIGHTLY_PASSWORD} ${FTP_DOMAIN};
    fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    - secure: DgFzibKfjjD4v6zP51sjyP+chyBNKA6D3LHz4+pKN2mSBLSFeqK29z+38TlIOJHSpq6pWdvxqHjn+vQuYV1v/oqri0AVpo0kxFojtNaIFo1Dc/Sfv76V7X6p9+JaSRtKtqCjOV7QP9fftyUgSu1Bq67fwuv6QvDgOzdQIcV87bA=
  file_glob: true
  file: build/cpack/inexor-core-*.zip
  overwrite: true
  on:
    # Deploy only if build was caused by a tag push.
    tags: true
    condition: "$CC = clang"
    repo: inexorgame/inexor-core
