language: cpp
before_install:
  # Install dependencies
  - sudo apt-get update
  - sudo apt-get -y install build-essential zlib1g-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libenet-dev
  - sudo apt-get -y install mingw32

script:
  - (mkdir cmakebuild && cd cmakebuild && cmake $CMAKE_FLAGS .. && make -j5 && cd .. && rm -rf cmakebuild)

compiler:
  - clang
  - gcc
  
env:
  - CMAKE_FLAGS=
  - CMAKE_FLAGS=-DRELEASE_BUILD=1
  - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../src/platform_windows/linux-toolchain-mingw.cmake -DMINGW_TYPE=classic"
  - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../src/platform_windows/linux-toolchain-mingw.cmake -DRELEASE_BUILD=1  -DMINGW_TYPE=classic"

notifications:
  webhooks: http://n.tkte.ch/h/2910/Rm7oDLYIC1icyntUug11eWi1
    on_success: always
    on_failure: always
    on_start: change
    on_pending: never
