version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game

platform: 
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects\inexor-game
  - cmd: git submodule update --init

# scripts to run before build
before_build:
  - cmd: cd C:\projects\inexor-game
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 13 only atm.
  - cmd: if "%platform%"=="Win32" set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015"
  - cmd: if "%platform%"=="x64"   set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64"
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: C:\projects\inexor-game\build\inexor.sln

  # enable MSBuild parallel builds
  parallel: true

  # MSBuild verbosity level (quiet|minimal|normal|detailed)
  verbosity: normal

after_build: # this is actually partly our before_deploy, but appveyor doesnt like that with dynamic artifacts
  
  - cmd: cd C:\projects\inexor-game\
  # We need to install the solution first
  - cmd: MSBuild build\install.vcxproj /t:build
  # create the nightly bundle .zip
  - cmd: if "%configuration%"=="Release" tool\appveyor_create_nightly.bat

deploy:
    # push our nightly bundle via ftp
  - provider: FTP
    protocol: ftp
    host: ftp.adrive.com
    folder: nightly
    username:
      secure: S278/OjFvlsW1p7m+cQKlA==
    password:
      secure: uDFAZRoczcpD1+he/RY3Ow==
    # push release binaries to GitHub if tag gets created (and create a release draft)
  - provider: GitHub
    auth_token:
      secure: vIfb9LX3nWCSRefUqY4JJL3hSosnPgKAbmGejFBL+C9GtHJKSuPLU6aMCrR79hPM
    draft: true
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only


# Note: on_success gets executed last
on_success: #we atm do not use it as test_script: bc if it fails then it signals a failed build
  - cmd: cd C:\projects\inexor-game\
  # run the unit test executable.
  - cmd: tool\appveyor_test.bat
