version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 2

platform:
 # - Win32
  - x64

configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - appveyor-retry choco install doxygen.portable
  - cmd: python -m pip install conan
  - cmd: set "MAIN_FOLDER=C:\projects\inexor-game"
  - cmd: cd %MAIN_FOLDER%
  - cmd: git submodule update --init
  # set INEXOR_VERSION (used in cmakes package creation process) based on the last tag found.
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" ( set "INEXOR_VERSION=%APPVEYOR_REPO_TAG_NAME%" )
  - cmd: if "%APPVEYOR_REPO_TAG%"=="false" ( set "INEXOR_VERSION=development" )

# scripts to run before build
before_build:
  - cmd: cd C:\projects\inexor-game
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 14 2015 only atm.
  - cmd: if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015" && set "arch_str=x86" )
  - cmd: if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64" && set "arch_str=x86_64")
  - cmd: if %configuration%==Debug (set "runtime_str=MTd")else (set "runtime_str=MT")
  - cmd: set "args=-DBUILD_CLIENT=1 -DBUILD_SERVER=1 -DBUILD_MASTER=1 -DBUILD_TEST=1 -DCREATE_PACKAGE=1"
  # Only deploy a bundle with the media folder if the branch is master (and its not a pr)(and its a Release build):
#  - cmd: if "%configuration%"=="Release" if "%APPVEYOR_REPO_BRANCH%"=="master" if defined APPVEYOR_PULL_REQUEST_NUMBER set "args=%args% -DPACKAGE_INCLUDE_MEDIA=1"
  - cmd: conan remote add inexor https://api.bintray.com/conan/inexorgame/inexor-conan --insert
  - cmd: conan install .. --scope build_all=1 --scope create_package=1 --build=missing -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration%
  - cmd: cmake .. -G "%CMAKE_GENERATOR_NAME%" %args% -DCPACK_GENERATOR="ZIP"
  #"NSIS;7Z"

build:
  project: C:\projects\inexor-game\build\PACKAGE.vcxproj
  # enable MSBuild parallel builds
  parallel: true

artifacts:
  # pushing a single file
  - path: build\Inexor-*.zip
#  - path: build\Inexor-*.exe

deploy:
    # push our nightly bundle via ftp
 # - provider: FTP
 #   protocol: ftp
 #   host: inexor.org
 #   username:
 #     secure: rpQyxcVaaqNxDvYQlGP/eA==
 #   password:
 #     secure: aBNw6S6n1MqCfw/0S2vhDA==
    # push release binaries to GitHub if tag gets created (and create a release draft)
  - provider: GitHub
    auth_token:
      secure: mILffF4R/yXcj1hSZzZq1HoLe2aScWVuUpCYvkDqLKStI7JHiLt5yb7w2DPo+HF0
    draft: false
    prerelease: true
    # Override files if there are any already.
    force_update: true
    on:
      # do only deploy on tag push
      appveyor_repo_tag: true
      configuration: Release

# Notify npm about the new release
# Note: the "        " lines which look like indentation errors are there for a reason (yaml)!
after_deploy:
  - ps:|
            echo "starting NPM deployment"
            if ($ENV:APPVEYOR_REPO_TAG -eq "true")
            {
              if ($ENV:CONFIGURATION -eq "Release" )
              {
                $package_json = "C:\projects\inexor-game\package.json"
                
                
                $package_version = $ENV:APPVEYOR_REPO_TAG_NAME -replace "-alpha"
                
                (Get-Content $package_json) | ForEach-Object { $_ -replace "VERSION_PLACEHOLDER", $package_version } | Set-Content $package_json
                
                $package_name_extension = "windows64"
                
                (Get-Content $package_json) | ForEach-Object { $_ -replace "PLATFORM_PLACEHOLDER", $package_name_extension } | Set-Content $package_json
                
                "@inexorgame:registry=https://registry.npmjs.org/`n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
                iex "npm pack"
                iex "npm publish --access public"
                
                echo "published to NPM"
              }
            }
            
            
  

test_script:
  - C:\projects\inexor-game\build\bin\unit_tests.exe
