version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game

platform: 
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - if defined APPVEYOR_PULL_REQUEST_NUMBER set "IS_PR=True"
  - if "%APPVEYOR_REPO_NAME%"=="inexor-game/code" set "IS_MAIN_REPO=True"
  - if "%IS_MAIN_REPO%"=="True" if "%IS_PR%"=="True" set "SKIP_BUILD=1"
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - appveyor-retry choco install doxygen.portable
  - cmd: python -m pip install conan
  - cmd: set "MAIN_FOLDER=C:\projects\inexor-game"
  - cmd: cd %MAIN_FOLDER%
  - cmd: git submodule update --init

# scripts to run before build
before_build:
  - cmd: cd C:\projects\inexor-game
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 14 2015 only atm.
  - cmd: set "config_cmake_targets=-DBUILD_GLUEGEN=0 -DBUILD_MASTER=1 -DBUILD_SERVER=1 -DBUILD_CLIENT=1"
  - cmd: if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015" && set "arch_str=x86" )
  - cmd: if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64" && set "arch_str=x86_64")
  - cmd: if %configuration%=="Debug" (set "runtime_str=MTd")else (set "runtime_str=MT")
  # TODO: debug build with MTd
  - cmd: conan install .. --build=missing -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration% 
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" %config_cmake_targets% ..

build:
# cmakes placeholder project to silence appveyor complaining about us using the cli
  project: C:\projects\inexor-game\build\ZERO_CHECK.vcxproj
  # enable MSBuild parallel builds
# parallel: true

after_build: # this is actually partly our before_deploy, but appveyor doesnt like that with dynamic artifacts
  - cmd: cd C:\projects\inexor-game\
  # Start the build here instead of in build to be able to finetune it:
  - cmd: if not defined SKIP_BUILD  msbuild C:\projects\inexor-game\build\install.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m
  # create the nightly bundle .zip
  - cmd: if not defined SKIP_BUILD if "%configuration%"=="Release" tool\appveyor_create_nightly.bat

deploy:
    # push our nightly bundle via ftp
  - provider: FTP
    protocol: ftp
    host: inexor.org
    username:
      secure: rpQyxcVaaqNxDvYQlGP/eA==
    password:
      secure: aBNw6S6n1MqCfw/0S2vhDA==
    # push release binaries to GitHub if tag gets created (and create a release draft)
  - provider: GitHub
    auth_token:
      secure: vIfb9LX3nWCSRefUqY4JJL3hSosnPgKAbmGejFBL+C9GtHJKSuPLU6aMCrR79hPM
    draft: true
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only


# Note: on_success gets executed last
on_success: #we atm do not use it as test_script: bc if it fails then it signals a failed build
  - cmd: cd C:\projects\inexor-game\
  # run the unit test executable.
  - cmd: tool\appveyor_test.bat
