version: 0.{build}
clone_depth: 1
clone_folder: C:\projects\inexor-game
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Maximum number of concurrent jobs for the project
max_jobs: 2

platform:
 # - Win32
  - x64

configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# scripts that run after cloning repository
install:
  - appveyor-retry choco install doxygen.portable
  - cmd: python -m pip install conan
  - cmd: set "MAIN_FOLDER=C:\projects\inexor-game"
  - cmd: cd %MAIN_FOLDER%
  - cmd: git submodule update --init
  # set INEXOR_VERSION (used in cmakes package creation process) based on the last tag found.
  - cmd: git fetch origin 'refs/tags/*:refs/tags/*'
  - cmd: for /F "tokens=* USEBACKQ" %%F in (`git rev-list --tags "--max-count=1"`) do (set HELPER_TAGLIST=%%F)
  - cmd: for /F "tokens=* USEBACKQ" %%F in (`git describe --tags %HELPER_TAGLIST%`) do (set INEXOR_VERSION=%%F)

# scripts to run before build
before_build:
  - cmd: cd C:\projects\inexor-game
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 14 2015 only atm.
  - cmd: if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015" && set "arch_str=x86" )
  - cmd: if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64" && set "arch_str=x86_64")
  - cmd: if %configuration%==Debug (set "runtime_str=MTd")else (set "runtime_str=MT")
  - cmd: set "args=-DBUILD_CLIENT=1 -DBUILD_SERVER=1 -DBUILD_MASTER=1 -DBUILD_TEST=1 -DCREATE_PACKAGE=1"
  # Only deploy a bundle with the media folder if the branch is master (and its not a pr)(and its a Release build):
#  - cmd: if "%configuration%"=="Release" if "%APPVEYOR_REPO_BRANCH%"=="master" if defined APPVEYOR_PULL_REQUEST_NUMBER set "args=%args% -DPACKAGE_INCLUDE_MEDIA=1"
  - cmd: conan install .. --scope build_all=1 --scope create_package=1 --build=missing -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=%runtime_str% -s arch=%arch_str% -s build_type=%configuration% 
  - cmd: cmake .. -G "%CMAKE_GENERATOR_NAME%" %args% -DCPACK_GENERATOR="ZIP"
  #"NSIS;7Z"

build:
  project: C:\projects\inexor-game\build\PACKAGE.vcxproj
  # enable MSBuild parallel builds
  parallel: true

artifacts:
  # pushing a single file
  - path: build\Inexor-*.zip
#  - path: build\Inexor-*.exe

deploy:
    # push our nightly bundle via ftp
 # - provider: FTP
 #   protocol: ftp
 #   host: inexor.org
 #   username:
 #     secure: rpQyxcVaaqNxDvYQlGP/eA==
 #   password:
 #     secure: aBNw6S6n1MqCfw/0S2vhDA==
    # push release binaries to GitHub if tag gets created (and create a release draft)
  - provider: GitHub
    auth_token:
      secure: vIfb9LX3nWCSRefUqY4JJL3hSosnPgKAbmGejFBL+C9GtHJKSuPLU6aMCrR79hPM
    draft: false
    prerelease: true
    # Override files if there are any already.
    force_update: true
    on:
      # release from master branch only
      branch: master
      # do only deploy on tag push
      appveyor_repo_tag: true
      configuration: Release

test_script:
  - C:\projects\inexor-game\build\bin\unit_tests.exe
